### ISSUE TITLE
[메인페이지] 메인페이지의 뷰를 구현합니다.

### ISSUE THREAD

**Issue by hoeun0723** [PJX-2024-2/PJX-Client#13]
## ✨어떤 기능인가요?
>Figma로 그려진 서비스의 UI 를 구현합니다. (메인페이지)
## ✔️TODOS
- [x] 달력 컴포넌트 생성
- [x] GNB 생성
- [ ] 지출 작성 무한스크롤탭 생성
- [x] 한달 지출 목표 컴포넌트 생성
## 🎶참고할 만한 자료
- 피그마 화면
