### ISSUE TITLE
[온보딩] 온보딩 페이지 뷰 퍼블리싱

### ISSUE THREAD

**Issue by P1su** [PJX-2024-2/PJX-Client#18]
## ✨어떤 기능인가요?
>추가하려는 기능에 대한 간단한 설명을 해주세요

온보딩 화면 뷰를 구현합니다.

## ✔️TODOS
- [ ] 퍼널구조 적용을 위한 훅과 컴포넌트 생성
- [ ] 단계별 컴포넌트 구현
- [ ] 온보딩 페이지에서 퍼널을 통한 렌더링

## 🎶참고할 만한 자료
>공식 문서, 개발 블로그, 강의 자료 등 자유롭게 첨부해주세요.
