### ISSUE TITLE
[chore] 폴더 구조 형성 및 라우트 설정

### ISSUE THREAD

**Issue by P1su** [PJX-2024-2/PJX-Client#3]
## ✨어떤 기능인가요?
>추가하려는 기능에 대한 간단한 설명을 해주세요

전체적인 폴더 구조를 설정하고, 라우트를 설치하여 예시 코드를 작성합니다.

## ✔️TODOS
- [ ] 폴더 구조 형성
- [ ] react-router-dom 설치
- [ ] rotue 예시 코드 작성
- [ ] App.tsx 에 RouteProvider 적용

## 🎶참고할 만한 자료
>공식 문서, 개발 블로그, 강의 자료 등 자유롭게 첨부해주세요.
