### ISSUE TITLE
[마이페이지] 마이페이지 뷰 제작

### ISSUE THREAD

**Issue by P1su** [PJX-2024-2/PJX-Client#32]
## ✨어떤 기능인가요?
>추가하려는 기능에 대한 간단한 설명을 해주세요

마이페이지 뷰를 제작합니다. 

## ✔️TODOS
- [ ] 마이페이지 첫 화면 제작
- [ ] 또래 친구 목록 화면 제작
- [ ] 내 정보 수정 페이지 제작
## 🎶참고할 만한 자료
>공식 문서, 개발 블로그, 강의 자료 등 자유롭게 첨부해주세요.
