### ISSUE TITLE
[알림] 알림 페이지 뷰 구현

### ISSUE THREAD

**Issue by P1su** [PJX-2024-2/PJX-Client#35]
## ✨어떤 기능인가요?
>추가하려는 기능에 대한 간단한 설명을 해주세요

알림 페이지 뷰를 구현합니다.

## ✔️TODOS
- [ ] 페이지 스타일 설정
- [ ] 알림 컴포넌트 제작
- [ ] 알림 여부에 따른 조건부 렌더링
## 🎶참고할 만한 자료
>공식 문서, 개발 블로그, 강의 자료 등 자유롭게 첨부해주세요.
