### ISSUE TITLE
[api 연결] 온보딩 닉네임 작성 api 연결

### ISSUE THREAD

**Issue by P1su** [PJX-2024-2/PJX-Client#49]
## ✨어떤 기능인가요?
>추가하려는 기능에 대한 간단한 설명을 해주세요

온보딩에서 닉네임을 입력하여 서버에 전송하는 api 코드를 작성합니다.

## ✔️TODOS
- [ ] 온보딩 단계 간소화 작업
- [ ] get으로 닉네임 중복 여부 확인하기
- [ ] post 로 닉네임 등록하기
## 🎶참고할 만한 자료
>공식 문서, 개발 블로그, 강의 자료 등 자유롭게 첨부해주세요.
