### ISSUE TITLE
[chore] theme 설정

### ISSUE THREAD

**Issue by P1su** [PJX-2024-2/PJX-Client#7]
## ✨어떤 기능인가요?
>추가하려는 기능에 대한 간단한 설명을 해주세요

theme 을 설정합니다. 

## ✔️TODOS
- [ ] theme.ts  파일 생성
- [ ] 예제 코드 작성 후 주석 처리
- [ ] Styles 컴포넌트에 ThemeProvider 적용하기
## 🎶참고할 만한 자료
>공식 문서, 개발 블로그, 강의 자료 등 자유롭게 첨부해주세요.
